import type { HudCommandId } from "./renderHud";

export function hudCommandCode(command: HudCommandId, race: "human" | "orc"): string {
  const human = race === "human";
  const codeByCommand: Record<HudCommandId, string> = {
    "cancel-queue": "Escape",
    "build-basic-page": "KeyB",
    "build-advanced-page": "KeyV",
    "build-page-cancel": "Escape",
    "move": "KeyM",
    "train-worker": "KeyT",
    "upgrade-town-center": "KeyU",
    "upgrade-guard-tower": "KeyG",
    "upgrade-cannon-tower": "KeyO",
    "train-minuteman": "KeyM",
    "stop": "KeyS",
    "hold-position": "KeyH",
    "attack-move": "KeyA",
    "attack-ground": "KeyG",
    "patrol": "KeyP",
    "follow": "KeyF",
    "repair": "KeyR",
    "detonate": "KeyD",
    "explore": "KeyX",
    "harvest": "KeyH",
    "return-goods": "KeyG",
    "train-melee": "KeyM",
    "train-ranged": "KeyR",
    "train-ranged-veteran": human ? "KeyR" : "KeyB",
    "train-cavalry-veteran": human ? "KeyP" : "KeyO",
    "train-critter": "KeyC",
    "build-farm": "KeyF",
    "build-barracks": "KeyB",
    "build-lumber-mill": "KeyL",
    "build-blacksmith": "KeyS",
    "build-wall": "KeyW",
    "build-advanced": human ? "KeyA" : "KeyO",
    "build-guard-tower": "KeyT",
    "build-cannon-tower": "KeyO",
    "build-shipyard": "KeyS",
    "build-foundry": "KeyF",
    "build-refinery": "KeyR",
    "build-oil-platform": "KeyU",
    "research-melee": "KeyZ",
    "research-armor": "KeyX",
    "research-ranged": "KeyC",
    "research-siege": "KeyQ",
    "research-paladin": "KeyP",
    "research-healing": "KeyH",
    "research-exorcism": "KeyE",
    "research-holy-vision": "KeyV",
    "research-flame-shield": "KeyL",
    "research-blizzard": "KeyB",
    "research-polymorph": "KeyP",
    "research-invisibility": "KeyI",
    "research-slow": "KeyS",
    "research-death-coil": "KeyD",
    "research-death-magic": "KeyW",
    "research-whirlwind": "KeyR",
    "research-raise-dead": "KeyG",
    "research-unholy-armor": "KeyU",
    "research-haste": "KeyH",
    "research-bloodlust": "KeyB",
    "research-runes": "KeyR",
    "research-eye-of-kilrogg": "KeyE",
    "train-cavalry": "KeyN",
    "train-tanker": "KeyY",
    "train-destroyer": "KeyD",
    "train-warship": "KeyJ",
    "train-transport": "KeyP",
    "train-submarine": "KeyS",
    "research-ship-cannon": "KeyC",
    "research-ship-armor": "KeyA",
    "load-transport": "KeyL",
    "unload-transport": "KeyU",
    "build-caster-building": human ? "KeyM" : "KeyT",
    "build-holy-building": human ? "KeyC" : "KeyL",
    "train-caster": "KeyA",
    "cast-heal": "KeyH",
    "cast-exorcism": "KeyE",
    "cast-holy-vision": "KeyV",
    "cast-fireball": "KeyF",
    "cast-flame-shield": "KeyL",
    "cast-blizzard": "KeyB",
    "cast-polymorph": "KeyP",
    "cast-invisibility": "KeyI",
    "cast-slow": "KeyS",
    "cast-death-coil": "KeyD",
    "cast-death-and-decay": "KeyW",
    "cast-whirlwind": "KeyR",
    "cast-raise-dead": "KeyG",
    "cast-unholy-armor": "KeyU",
    "cast-haste": "KeyH",
    "cast-bloodlust": "KeyB",
    "cast-bloodlust-double-head": "KeyB",
    "cast-runes": "KeyR",
    "cast-runes-double-head": "KeyR",
    "cast-eye-of-kilrogg": "KeyE",
    "cast-eye-of-kilrogg-double-head": "KeyE",
    "build-air-building": human ? "KeyG" : "KeyD",
    "train-air": "KeyI",
    "build-siege-lab": human ? "KeyI" : "KeyA",
    "train-demolition": "KeyE",
    "train-scout-air": "KeyZ",
    "train-siege": "KeyQ"
  };
  return codeByCommand[command];
}
